apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: planka
  namespace: storage
spec:
  instances: 1

  inheritedMetadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "productivity"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "productivity"

  postgresql:
    pg_hba:
      - hostssl planka planka all scram-sha-256

  bootstrap:
    initdb:
      database: planka
      owner: planka

  enableSuperuserAccess: true

  storage:
    storageClass: longhorn-retain
    size: 5Gi
