apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: riven
  namespace: storage
spec:
  instances: 1

  inheritedMetadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media"

  postgresql:
    pg_hba:
      - hostssl riven riven all scram-sha-256

  bootstrap:
    initdb:
      database: riven
      owner: riven
      postInitSQL:
        - ALTER USER riven WITH SUPERUSER;

  enableSuperuserAccess: true

  storage:
    storageClass: longhorn-retain
    size: 5Gi
