apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SECRET_PLANKA_KEY: ENC[AES256_GCM,data:g7rOyn2B+WVPzsQpDkhCGsK67s4OsBFy8b+nJM8jH3XZjY/PERySBAWYzjo=,iv:gqxJVT7YD+Q/MSmWsWm+dTovMUzSR40RpesnR5D6n9M=,tag:9OZ0u0gsV9MactQ1MSBPJg==,type:str]
    SECRET_PLANKA_ADMIN_PASSWORD: ENC[AES256_GCM,data:eac73bt1N+I2gxrZglN7o/Ug2j4=,iv:IkFhkhjhb9wf2aoYpHouGn8PgB94OJ6HgzXTCkuEGIM=,tag:7PDM/gRApMP4on3iY7fQ0g==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:GfQcSFKO12sgsJ+vhOOiAvNvcC0=,iv:FsUSnweEWI4A32JABBu11pxlqB6u5/jQkdwIqSLCw8g=,tag:FuWHrK3ECEWv/o25Fcr+ag==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:W9yPfe8VmltDG+Yx,iv:j3kkxHB5fY6FCMvPp9NOdDLDHFlGRP7MJxVE3KrUBmY=,tag:zY3Ic+TnqxuUJiygiTT58w==,type:str]
    SECRET_S3_ACCESS_ID: ENC[AES256_GCM,data:U3zclJikzx5SlSL+npXCnL7jeSyBBcbneQ==,iv:vr4or9fccPOmmaDty/pMZUFXr3U1hl7Luxj8xb6lFks=,tag:A3sjz6RNtPmXpJFzThvhrw==,type:str]
    SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:GPBRHfA/nC3yRGj77Se+kJsgY2K88w5X4P97PEI6UQ==,iv:uHs2tKRd2+1Co8IrjtKpAYk1k0gDoLL6YcvZxewuJco=,tag:FDyywUZaaaFO83P8VTTzQQ==,type:str]
    SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:GEq7x3BYhZAKB53Rdh/6T8eUry3dsY1tnvPpBPtbXQuIJQ8iEhamnls=,iv:IJlGbGXWkJP+FVayPt10nHtFi/d8MvtiyKbe3mpbcJM=,tag:W5mC15k6O7kDg7BdHRW2Pg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:/r3AxXTj1F+zUQ==,iv:9/EwmiHtK5F3jtmSXzNihiOsSILaDcovr95egi+Z0mk=,tag:tPBW6h+EMthf099A83Aogg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:U27qSaHTYyHhL1BXA5IN0SDf,iv:9B/bXxT5frU7lnrIBd9wS5lDb7RV3Rmagme/qx69Uas=,tag:dQqqwfxGY8PM303i0eB4eg==,type:str]
    SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:fdyCEZIyUMoJFO5fgtLLcFs44yRfiFTgkGGaLtxJbc+4TSGjgcsKsnhm+Le4Qlme+6ZZu4Y=,iv:pe5ee6l/l/O3+fzwLBu2wsX+2fm2TesPjmXcmzx/tq4=,tag:arjsLiYPKvB30ko6unjr+g==,type:str]
    SECRET_RADARR_API_KEY: ENC[AES256_GCM,data:x/55thWoHoyf7w2asTIDTMYMt2SIQXPAG6Ks3+yfaXI=,iv:iu0VijfV56A8A72ap3YPi7v1fgH3KlaDxamJpsCwKUM=,tag:3q3j2M/dsU1oBUcw9Ks+cg==,type:str]
    SECRET_SONARR_API_KEY: ENC[AES256_GCM,data:ffLvLQs67TzG3AlW2p3yTitKbqlP9oWrYnLZ5ag457s=,iv:jyx2YOpBtnN7xp0DujbRI+iA8V5KgQT6JM1u84IonGo=,tag:LjLUdLn0LpVIgJeiidftRA==,type:str]
    SECRET_PROWLARR_API_KEY: ENC[AES256_GCM,data:iGaWzfpcIS82t9qNWsiP2pqk8ALvjlyO9oiC++j/ZG0=,iv:xWUCMJTSSeMBi0Gldb6SFTq4q8V/UZtS7AiXIyJWc94=,tag:Bls+isV4R2FeyyymsNSmFQ==,type:str]
    SECRET_BAZARR_API_KEY: ENC[AES256_GCM,data:QTtEC+8ItNGowNvEm/KpTXKhmJHRbshLAp38fGZH0w8=,iv:nj2937hpgPAibiGIg9+qpSLt+xNw4Sq5e+Ss36niFh0=,tag:r9Dk2NFq0YYYIJ9Kb/iQOg==,type:str]
    SECRET_SEERR_API_KEY: ENC[AES256_GCM,data:GKa4h19v3yF3/NUuEPDuUP2Cqw+Dvbw/CtxIiFYPDn9QQScrxCaG7afe7FOfzBRBDd70UJ5TBECvf6thSpDn5cvWGTU=,iv:POfZvoLwcsT6H6qcnYkvWi9VWajhfrMvMy/oZLkMLa8=,tag:G/fyjd9UKrGeju80G9eHUQ==,type:str]
    SECRET_JELLYFIN_API_KEY: ENC[AES256_GCM,data:HShES3ic6doh/vl6EGT/6JGNFt/SUFQerTUjEyknF4o=,iv:euxmB/QE+i/IPQmw5pjQ4gMxjl+5oVrKfnwPxyzYh+4=,tag:YfFDRZdUy/vYD/h9FvBzUA==,type:str]
    SECRET_HOMEASSISTANT_API_KEY: ENC[AES256_GCM,data:hp7bRlcYAvNUCP/tWTxP52gVIOYFEF/abePKXCtyWaD35LTKrALpDsbbFbENMAe24twQlP2TjC2bdhkeWHpxHdvLuB07cGfq1QnSvKg1owIkNSV/fqi3BEKugoXbEhhPwJNWTS/ykCW5My6LJedYu3BkMtCRhjvQCkZOrRq5xUdImo7Q/+r1qS38e34aACRhDrtJ6UBzT3AaDsFfoQDvKB0luJY4ER4KqkqjMsap7ZKj/z2XFNTr,iv:Sbh0X4H3qY0lee1nTz/7JkjsiUf6tsxsrK3fdEFDjM8=,tag:yL235BGW2qBdbbomgEhleQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OWkwK2R0SDZIdkhwYU5l
            SEduK0k3QnpmMWxsaUp0akhZYndxQjdlTFNrClFlUmVvTlJSbjcrbFJsNnhJMy93
            SE9TaUVBUGZBOExKZWVYWFpSdTNFOE0KLS0tIC8zblh1bG1TdzVCMlJLWnFKdkxK
            Q1FPSDM0aFBtNTAvWndVNHUwdGFrUkkKzaXWGDvF+0da9izFIC1KA7qW0yLNPoqO
            emNFB3vVKJuusueuH03eMp7peKDz9awFVTRzPt/fXzjmco5JWjewRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16aml0530sew4hsdqka7cgqy4etupmh97d59z9n4567spxn767ags63ahlv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T11:24:52Z"
    mac: ENC[AES256_GCM,data:GBU3VKoa7Z7tr9tveG/NaXE/yuD0JpHrQGlh4qQMlu3qNoBUk1mp0FhUWACOnZD0ByrfveXkyu2s5oPVnUh6ini6sOrjZ4kMoO9/kVY4ouhkLqwBMEQ74+aFPthlTJyXqrRfL+AwpnGPeWNOBL16V9WBaAZkO/rI2HEg7Mqm7RE=,iv:yMnkdFhNZEJvCuU+pOBFlD5O/CnQ5SA+Fcm5sbdBsIk=,tag:NA5HeDMrpJ19m/3omcRUPA==,type:str]
    version: 3.13.3
