apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SECRET_RIVEN_API_KEY: ENC[AES256_GCM,data:xn5udnv804X+EWWc2z21FQZrwM83riEqUBJv46WR4iwc8vAWiJkap99ehN4=,iv:s1s4jPAJehdWf/Su4b60/n7dTObQ5mMyeSadQpMBYvo=,tag:lFyfX0JbFA659hiAELYVDA==,type:str]
    SECRET_RIVEN_AUTH: ENC[AES256_GCM,data:pbyFN9DbaB4URudsfNU5YESAhrxe5WwtpdS8mzasGE+KB4CT/9tJta/rarM=,iv:nXObQ2RusQKnCa7jqE5JidRC453+02j7VQsfujLKNE4=,tag:Fun0qWvTra5/1+8tr20+fQ==,type:str]
    SECRET_PLANKA_KEY: ENC[AES256_GCM,data:E6sG2rWqavEIZUargYNV8sGZG/sx9hgpvtsu9vkzaD7/f9yn8ZtPm6lXYV4=,iv:GFtdN303GlQK3NuMbRKf5Cy2bGSrQRqS6A/Xa9+B9K4=,tag:u/zRKHgUmelamfbjgSwO+Q==,type:str]
    SECRET_PLANKA_ADMIN_PASSWORD: ENC[AES256_GCM,data:9Gg9YJpmF8f7+juFP6pJ+yYfsBs=,iv:jvxeao0Isv48rsjnCuRrASqWnvX99q6aI/bcdA3gPQE=,tag:6+wSFEnaGVWDs+TBTL10wQ==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:Tvd9tqSD1o9WgrqrVBBF6Jqs1Mo=,iv:BzuhPCU2ZCUj0nt6T1aXDkc481JmhPyeR2fVFGbXSYQ=,tag:BF7A8HKBSK2NlBtYBFgtFQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:PHrUarUN96vq7fys,iv:Uz1T7JRyezOpqvM6hj4Sj6Fd6c9mYrAfO2NFg6o0pOA=,tag:joWQZmSVhHIjiq1yjRmwew==,type:str]
sops:
    age:
        - recipient: age16aml0530sew4hsdqka7cgqy4etupmh97d59z9n4567spxn767ags63ahlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZHlWR3ZUQ2hleGVvb0Uz
            bUVHZWdMNzM4KzZheFlEazdqQ2xHN3d1N0VzCnRKMC9SMC9Ram9HYlk4RDdiNlJV
            cmJaUVoxNXRkaHNxVlRqS1hHRXVZYVUKLS0tIEhFSjc1YUo1amtmY3oxV2xzMk8w
            NFo1aUw5RXBvZXppYXlZYUZwZjZqOXMKYQnbD8aDW+ZOUEXZOBkRAw9n6dhGSi3S
            d206OyB6+1VmPgJQF93IY5oWgxiYLcooxtCkwPgNfaYUfp6H80Wjew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T11:29:31Z"
    mac: ENC[AES256_GCM,data:B0k+9jnn2evvd9Tp339wIFWQWtBYvuF5xrMDIw9F59Q7TwTBJmrA1ArEgTvDRsXbswHoLrW4FiYGC0x7/3sT4Oc8R3XC4RrHraCxpv9t3RCOovWpXCJU8WymD9sW3NN/RJveZjvqfmF3uiRNCY1jkU3GDqM/qE6rBgrw83nSpSE=,iv:ALieKBOkuqEMHF3cTav+KpjqWhj2I1qQCRN4nee5860=,tag:99aWcsSYvL+DYpekM4LihQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
