apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SECRET_PLANKA_KEY: ENC[AES256_GCM,data:JTYPfszjGgEDND/zucRGEs1/rg6lf9zoAlY1dtpOyrRIw29AtoaauSdv81w=,iv:m/HTIcZtE5PWWVG+f+m+jkg4Of/bm89ceLQ5cbWygQI=,tag:rKGZ2elGuUe4Hg1KtZ2zeg==,type:str]
    SECRET_PLANKA_ADMIN_PASSWORD: ENC[AES256_GCM,data:9P2Ig4ehxElEhXzFPNw6WSEt6J4=,iv:s0Tc0CY8m9RUQiPyqBAzSCzZ3PFqgckDNz4YIPUBc5k=,tag:ekhdMDH9Qq9973XtgcysbA==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:zqUpEHwlU8H+6CyUOueUaOtZZ3A=,iv:yMq0A+uvnwBky1qPUts4Trnlk2tkkA+AWEgDog7w/1I=,tag:pPq/s3teK4+ean/seRL8jg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:y/PDlg+DWwl9OwS4,iv:0NkWcLzPM+3nVjrpP+o2HOtbMNRnY6/CZZgaK0gMvEg=,tag:29pocbbwEaK46iCVSLDOtw==,type:str]
    SECRET_S3_ACCESS_ID: ENC[AES256_GCM,data:kdsJBcfTEBbbqzS+YR0fftB5FlLO7eKOcA==,iv:KCfs73R8uUqH/h9gw3GZtNusiHlUmAcB8sbHPwYUPRg=,tag:WXsjfqmrfFg6dh57PHSOVQ==,type:str]
    SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:vk57oa1uKcbOHF8OO/1HmbhXuwGYw8QIOHBykWXURA==,iv:8xGno1FacllW2MxsDaOMs7ckIQv8TPfjrcgP8olN7ao=,tag:PqU2afF3kELiSrKNlVCseQ==,type:str]
    SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:RAwDs+suF/PAC2jikaFn0oxE8qoSjlC7PfYFpdYBINBdByswYil+HRg=,iv:08/14xjO6M8/p9awUbtD2SbaHVR4NtetFPJgSjnLU9o=,tag:OtFG5vtsIlK03GFOlasVzA==,type:str]
sops:
    age:
        - recipient: age16aml0530sew4hsdqka7cgqy4etupmh97d59z9n4567spxn767ags63ahlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeGtwY003cW5LU1d0d0NX
            UHNxQjd2aTVsbjdEM0JqVzMvWkxaOUR0VkdjCnlXbC9kQlZFd0cyUUN1S2Y1WEhn
            TUlaOE1oT0FPUEVTVGZDK2ZybkVxbUkKLS0tIGJtcXJXTlI5NllBbldlaVZ1UjVk
            M3djQ0JlMUxTSGl1SjFNZ3hzZkxCQUkKDFR897c25ZEcj45CwbJCTrs0kyquKFl8
            KkcfjkL8Socg2ah0F3/tXZbHo5ksDIeOv7PS7yAKYs2ofnY/QegqpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T09:04:29Z"
    mac: ENC[AES256_GCM,data:Gp880xIz7jjiCQ3C9WiTjbicWncnfxZHa6C0o+G9Dm114y5vtA4js4jD47NVUxscHPI1nK5FR5jbt/sRj/RL2SI1DemskrSvhG5nvS2O4H6lb1xjYm8IAR1bo6PQVfozkGpvC69OjD2J8aTPC6/IJhVHaUxrwXiIA5GcqTWR2No=,iv:9OyHiWJ3TKhQQGacL3T2Phdd4oxYYXR0V4CX7ZsqPIQ=,tag:joAsI8Y1rhxL8Fz8h30WyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
