apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: planka-app
  namespace: productivity
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`planka.tailnet.core.local`)
      kind: Rule
      services:
        - name: planka-app
          port: 1337
      middlewares:
        - name: trusted-only
          namespace: kube-system
  tls: {}
