apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: shared
  namespace: storage
spec:
  metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "productivity"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "productivity"

  postgresVersion: 16

  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: longhorn-retain
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

  users:
    - name: planka
      databases:
        - planka

