---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 1m0s
  chart:
    spec:
      chart: alloy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      version: 1.6.0
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      type: daemonset
      tolerations:
        - operator: Exists

    alloy:
      configMap:
        create: false
        name: alloy-config
        key: config.alloy
