---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: kube-system
spec:
  secretName: wildcard-tls
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-wildcard-cert
  namespace: kube-system
spec:
  secretName: public-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_PUBLIC_DOMAIN}"
    - "*.${SECRET_PUBLIC_DOMAIN}"
