---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      version: 8.6.2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    adminUser: admin
    adminPassword: grafana

    persistence:
      enabled: true
      storageClassName: longhorn-retain
      size: 1Gi

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: http://loki.monitoring.svc.cluster.local:3100
            access: proxy
            isDefault: true

    grafana.ini:
      server:
        root_url: https://grafana.tailnet.core.local
