name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # Every night at 3am CEST

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Bot
        uses: renovatebot/github-action@v46.1.10
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: ${{ github.repository }}
